modLoader="javafml" #mandatory

loaderVersion="${loader_version_range}" #mandatory

license="${mod_license}"

[[mods]] #mandatory

modId="${mod_id}" #mandatory

version="${mod_version}" #mandatory

displayName="${mod_name}" #mandatory

authors="Kuki2008"

description='''
This mod implements compatability between Agricraft Reloaded and Create
'''

# The [[mixins]] block allows you to declare your mixin config to FML so that it gets loaded.
[[mixins]]
    config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="[${neo_version},)" #mandatory
    ordering="NONE"
    side="BOTH"

# Here's another dependency
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="create"
    type="required"
    versionRange="[6.0.0,6.1.0)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="agricraft"
    type="required"
    versionRange="[4,)"
    ordering="AFTER"
    side="BOTH"

#[features.${mod_id}]
#openGLVersion="[3.2,)"
